# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: ziva_brain.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'ziva_brain.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10ziva_brain.proto\x12\tzivabrain\"b\n\x0fGenerateRequest\x12\x0e\n\x06prompt\x18\x01 \x01(\t\x12\x13\n\x0btemperature\x18\x02 \x01(\x02\x12\x12\n\nmax_tokens\x18\x03 \x01(\x05\x12\x16\n\x0estop_sequences\x18\x04 \x03(\t\"G\n\x10GenerateResponse\x12\x0c\n\x04text\x18\x01 \x01(\t\x12\x13\n\x0btoken_usage\x18\x02 \x01(\x05\x12\x10\n\x08\x66inished\x18\x03 \x01(\x08\x32\xa4\x01\n\x0c\x42rainService\x12\x45\n\x08Generate\x12\x1a.zivabrain.GenerateRequest\x1a\x1b.zivabrain.GenerateResponse\"\x00\x12M\n\x0eGenerateStream\x12\x1a.zivabrain.GenerateRequest\x1a\x1b.zivabrain.GenerateResponse\"\x00\x30\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ziva_brain_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_GENERATEREQUEST']._serialized_start=31
  _globals['_GENERATEREQUEST']._serialized_end=129
  _globals['_GENERATERESPONSE']._serialized_start=131
  _globals['_GENERATERESPONSE']._serialized_end=202
  _globals['_BRAINSERVICE']._serialized_start=205
  _globals['_BRAINSERVICE']._serialized_end=369
# @@protoc_insertion_point(module_scope)
